In [ ]:
#example 8-1, 8-2, 8-3 

#ให้ดูในหนังสือ

In [5]:
#example 8-4

from sklearn.preprocessing import LabelEncoder 
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np

df = pd.read_excel(r'data\traffic.xlsx')
#with pd.option_context('display.max_rows', 10): display(df)

#features => df[['Weather', 'TimeOfWeek', 'TimeOfDay']]
x = df.iloc[:, 0:3].apply(LabelEncoder().fit_transform)
y = df['TrafficJam']

model = GaussianNB()
model.fit(x, y)

#ก่อนจะทำนายผล ให้ตรวจสอบข้อมูล
#โดยแสดงผลออกมาดูว่า
#สตริงที่แต่ละค่านั้นถูกเข้ารหัสเป็นเลขอะไร
display(df.head())
display(x.head())

#เมื่อเขียนโค้ดมาถึงตรงนี้ เราต้องรันดูผลลัพธ์ก่อน แล้วค่อยเขียนโค้ดขั้นตอนต่อไป

#ถ้าเราต้องการทำนายผลสำหรับกรณี 
#Weather: Clear, TimeOfWeek: Workday, TimeOfDay: Lunch
#ก็กำหนดตัวเลขให้ตรงกัน เช่น
#'Clear' => 0, 'Workday' => 1, 'Lunch' => 1

x_predict = [[0], [1], [2]]  #np.array([0, 1, 1]).reshape(-1, 1)
y_predict = model.predict(x_predict)

print('Prediction => TrafficJam:', y_predict[0])
print('Accuracy:', '{:.2f}'.format(model.score(x, y)))

  Weather TimeOfWeek TimeOfDay TrafficJam
0   Clear    Workday   Morning        Yes
1   Clear    Workday     Lunch         No
2   Clear    Workday   Evening        Yes
3   Clear    Weekend   Morning         No
4   Clear    Weekend     Lunch         No

   Weather  TimeOfWeek  TimeOfDay
0        0           1          2
1        0           1          1
2        0           1          0
3        0           0          2
4        0           0          1

Prediction => TrafficJam: No
Accuracy: 0.83

In [2]:
#example 8-5

from sklearn.preprocessing import LabelEncoder 
from sklearn.naive_bayes import GaussianNB
import pandas as pd

df = pd.read_excel(r'data\traffic.xlsx')
#with pd.option_context('display.max_rows', 10): display(df)

#ต้องใช้ LabelEncoder เพื่อเข้ารหัสแต่ละคอลัมน์คอลัมน์แยกกัน
#เพราะแต่ละคอลัมน์เป็นสตริงคนละชุด
weather_encoder = LabelEncoder()
df['Weather'] = weather_encoder.fit_transform(df['Weather'])

tweek_encoder = LabelEncoder()
df['TimeOfWeek'] = tweek_encoder.fit_transform(df['TimeOfWeek'])

tday_encoder = LabelEncoder()
df['TimeOfDay'] = tday_encoder.fit_transform(df['TimeOfDay'])

x = df[['Weather', 'TimeOfWeek', 'TimeOfDay']]  #df.iloc[:, 0:3]
y = df['TrafficJam']
#with pd.option_context('display.max_rows', 8): display(df)

model = GaussianNB()
model.fit(x, y)

#ถ้าเราต้องการทำนายผลสำหรับกรณี 
#Weather: Clear, TimeOfWeek: Workday, TimeOfDay: Lunch
#หากจะทำนายผลค่าอื่นๆ ให้แก้ไขค่าที่นี่
weather = 'Clear'
tweek = 'Workday'
tday = 'Lunch'

#แต่ละคอลัมน์ต้องเข้ารหัสด้วยอินสแตนซ์เดิม
#เพื่อใช้ค่าอ้างอิงอันเดียวกัน
weahter_enc = weather_encoder.transform([weather])
tweek_enc = tweek_encoder.transform([tweek])
tday_enc = tday_encoder.transform([tday])

x_predict = [weahter_enc, tweek_enc, tday_enc]
y_predict = model.predict(x_predict)

print(f'Weather: {weather}, TimeOfWeek: {tweek}, TimeOfDay: {tday}')
print('TrafficJam:', y_predict[0])

print()
print('Accuracy:', '{:.2f}'.format(model.score(x, y)))

Weather: Clear, TimeOfWeek: Workday, TimeOfDay: Lunch
TrafficJam: No

Accuracy: 0.83

In [13]:
#example 8-6

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_excel(r'data\animals.xlsx')
with pd.option_context('display.max_rows', 10): display(df)

blood_encoder = LabelEncoder()
df['Blood_Temperature'] = blood_encoder.fit_transform(df['Blood_Temperature'])

#คอลัมน์ Give_Birth, Can_Fly, Have_Legs มีค่าเป็น Yes/No เหมือนกัน
#จึงสามารถเข้ารหัสด้วยค่าอ้างอิง หรือ Encoder เดียวกันได้
yes_no_encoder = LabelEncoder()
df['Give_Birth'] = yes_no_encoder.fit_transform(df['Give_Birth'])
df['Can_Fly'] = yes_no_encoder.transform(df['Can_Fly'])
df['Have_Legs'] = yes_no_encoder.transform(df['Have_Legs'])

water_encoder = LabelEncoder()
df['Live_In_Water'] = water_encoder.fit_transform(df['Live_In_Water'])

x = df[['Blood_Temperature', 'Give_Birth', 'Can_Fly', 
        'Live_In_Water', 'Have_Legs']]   #df.iloc[:, 1:6]

y = df['Species']

model = GaussianNB()
model.fit(x, y)

#ค่าที่ต้องการทำนายผล
blood = 'Warm'
birth = 'No'
fly = 'Yes'
water = 'Sometimes'
legs = 'No'

#ต้องเข้ารหัสด้วยอินสแตนซ์เดิม
blood_enc = blood_encoder.transform([blood])
birth_enc = yes_no_encoder.transform([birth])
fly_enc = yes_no_encoder.transform([fly])
water_enc = water_encoder.transform([water])
legs_enc = yes_no_encoder.transform([legs])

#Blood_Tem, Give_Birth, Can_Fly, Live_In_Water, Have_Legs
x_pred = [blood_enc, birth_enc, fly_enc, water_enc, legs_enc]
y_pred = model.predict(x_pred)

print('Prediction:', y_pred[0])

score = model.score(x, y)
print('Accuracy:', '{:.2f}'.format(score))

,Name,Blood_Temperature,Give_Birth,Can_Fly,Live_In_Water,Have_Legs,Species
0,Human,Warm,Yes,No,No,Yes,Mammals
1,Python,Cold,No,No,No,No,Reptiles
2,Bat,Warm,Yes,Yes,No,Yes,Mammals
3,Frog,Cold,No,No,Sometimes,Yes,Amphibians
4,Salmon,Cold,No,No,Yes,No,Fishes
...,...,...,...,...,...,...,...
15,Platypus,Warm,No,No,No,Yes,Mammals
16,Owl,Warm,No,Yes,No,Yes,Birds
17,Dolphin,Warm,Yes,No,Yes,No,Mammals
18,Eel,Cold,No,No,Yes,No,Fishes
19,Eagle,Warm,No,Yes,No,Yes,Birds

Prediction: Mammals
Accuracy: 0.90

In [12]:
#example 8-6 (2)

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_excel(r'data\animals.xlsx')
#with pd.option_context('display.max_rows', 10): display(df)

x = df.iloc[:, 1:6].apply(LabelEncoder().fit_transform)
y = df['Species']

model = GaussianNB()
model.fit(x, y)

display(df.head())
display(x.head())
#เมื่อเขียนโค้ดมาถึงตรงนี้ เราต้องรันดูผลลัพธ์ก่อน แล้วค่อยเขียนโค้ดขั้นตอนต่อไป

#ค่าที่ต้องการทำนายผล
#blood: 'Warm', birth: 'No', fly: 'Yes', water:'Sometimes', legs:'No'
#เทียบเป็นตัวเลข
#blood: 1, birth: 1, fly: 1, water: 2, legs: 0

x_pred = [[1], [1], [1], [2], [0]]
y_pred = model.predict(x_pred)

print('Prediction:', y_pred[0])

score = model.score(x, y)
print('Accuracy:', '{:.2f}'.format(score))

,Name,Blood_Temperature,Give_Birth,Can_Fly,Live_In_Water,Have_Legs,Species
0,Human,Warm,Yes,No,No,Yes,Mammals
1,Python,Cold,No,No,No,No,Reptiles
2,Bat,Warm,Yes,Yes,No,Yes,Mammals
3,Frog,Cold,No,No,Sometimes,Yes,Amphibians
4,Salmon,Cold,No,No,Yes,No,Fishes

   Blood_Temperature  Give_Birth  Can_Fly  Live_In_Water  Have_Legs
0                  1           1        0              0          1
1                  0           0        0              0          0
2                  1           1        1              0          1
3                  0           0        0              1          1
4                  0           0        0              2          0

Prediction: Mammals
Accuracy: 0.90

In [4]:
#example 8-7

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

df = pd.read_excel(r'data\sunburned.xlsx')
with pd.option_context('display.max_rows', 8): display(df)

#ใช้จัดเก็บอินสแตนซ์ LabelEncoder ของแต่ละคอลัมน์
encoders = []

#เนื่องจากคอลัมน์ที่จะเข้ารหัสนั้นอยู่ติดกัน
#จึงสามารถใช้ลูป for ได้
for i in range(0, len(df.columns) - 1):
    #สร้างอินสแตนซ์ของ LabelEncoder ที่จะใช้เข้ารหัสของคอลัมน์นั้น
    enc = LabelEncoder()
    
    #เข้ารหัสคอลัมน์ในลำดับนั้น
    df.iloc[:, i] = enc.fit_transform(df.iloc[:, i])
    
    #เก็บอินสแตนซ์ที่ใช้เข้ารหัสแต่ละคอลัมน์ไว้ในลิสต์
    encoders.append(enc)

with pd.option_context('display.max_rows', 10): display(df)    

x = df.iloc[:, 0:4]
y = df['Sunburned']

model = GaussianNB()
model.fit(x, y)

#ค่าที่จะทำนายผล
x_pred = ['Black', 'Dark', 'Average', 'No']

#เข้ารหัสแต่ละค่าที่จะทำนายผล
#ด้วยอินสแตนซ์เดิมที่เก็บไว้ในลิสต์
for i in range(0, len(df.columns) - 1):
    x_pred[i] = encoders[i].transform([x_pred[i]])

x_pred_a = np.array(x_pred).reshape(-1, 4) #หรือใช้ len(df.columns)-1

y_pred = model.predict(x_pred_a) 

for i in range(0, len(df.columns) - 1):
    #ถอดรหัสกลับไปเป็นสตริงที่เข้าใจได้เพื่อการแสดงผล
    s = encoders[i].inverse_transform(x_pred[i])   
    print(f'{df.columns[i]}: {s[0]}, ', end='')

print('Sunburned:', y_pred[0])

score = model.score(x, y)
print('Accuracy:', '{:.2f}'.format(score))

      Hair    Eye       Weight Lotion Sunburned
0    Black   Dark   Overweight     No        No
1      Red   Dark      Average     No       Yes
2   Blonde  Light   Overweight     No       Yes
3      Red  Light  Underweight     No       Yes
..     ...    ...          ...    ...       ...
10   Black  Light      Average    Yes       Yes
11  Blonde  Light  Underweight     No       Yes
12     Red   Dark      Average    Yes        No
13   Black  Light  Underweight     No       Yes

[14 rows x 5 columns]

    Hair  Eye  Weight  Lotion Sunburned
0      0    0       1       0        No
1      2    0       0       0       Yes
2      1    1       1       0       Yes
3      2    1       2       0       Yes
4      0    0       1       1        No
..   ...  ...     ...     ...       ...
9      2    1       0       1       Yes
10     0    1       0       1       Yes
11     1    1       2       0       Yes
12     2    0       0       1        No
13     0    1       2       0       Yes

[14 rows x 5 columns]

Hair: Black, Eye: Dark, Weight: Average, Lotion: No, Sunburned: No
Accuracy: 0.86